# Generated by Django 2.1.1 on 2018-11-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdetail_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Designation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
